name: Build Multi-Platform CLI

on:
  release:
    types: [published]  # Trigger when a release is published

jobs:
  build-and-release-cli:
    name: Build CLI for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: linux
            asset_name: intent-cli-linux
          - os: windows-latest
            target: windows
            asset_name: intent-cli-windows.exe
          - os: macos-latest
            target: macos
            asset_name: intent-cli-macos

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller build

      - name: Build package
        run: python -m build

      - name: Build CLI executable with PyInstaller
        run: |
          # Find and install the wheel file (since it should be in dist/ after build)
          pip install dist/*.whl
          pyinstaller --onefile --name ${{ matrix.asset_name }} src/intent_kit/__main__.py

      - name: Upload CLI executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: ${{ matrix.target == 'windows' && 'application/vnd.microsoft.portable-executable' || 'application/octet-stream' }}