name: Release Templates

on:
  release:
    types: [published]  # Trigger when a release is published

jobs:
  create-templates:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      ASSET_VERSION: ${{ steps.set-outputs.outputs.ASSET_VERSION }}

    steps:
      - uses: actions/checkout@v4

      - name: Extract version and create templates for each AI agent
        shell: bash
        run: |
          # Extract version from tag ref (removing 'refs/tags/' prefix and 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}  # Remove 'v' prefix if present
          echo "ASSET_VERSION=$VERSION" >> $GITHUB_ENV
          
          # Define AI agents to create templates for
          AGENTS=("copilot" "claude" "gemini" "cursor" "qwen" "opencode" "codex" "windsurf" "kilocode" "auggie" "roo" "codebuddy" "q")
          
          # Create templates directory if it doesn't exist
          mkdir -p templates_for_agents
          
          # For each agent, create an agent-specific templates directory
          for agent in "${AGENTS[@]}"; do
            # Create directories for different script types
            mkdir -p "templates_for_agents/${agent}/sh"
            mkdir -p "templates_for_agents/${agent}/ps"
            
            # Copy all templates to agent-specific directories
            cp -r templates/* "templates_for_agents/${agent}/sh/" 2>/dev/null || echo "No templates to copy for sh"
            cp -r templates/* "templates_for_agents/${agent}/ps/" 2>/dev/null || echo "No templates to copy for ps"
            
            # Create archives for each agent and script type
            if [ -d "templates_for_agents/${agent}/sh" ] && [ "$(ls -A templates_for_agents/${agent}/sh)" ]; then
              (cd "templates_for_agents/${agent}/sh" && tar -czf "../../../intent-kit-template-${agent}-sh-v${VERSION}.tar.gz" .)
              (cd "templates_for_agents/${agent}/sh" && zip -r "../../../intent-kit-template-${agent}-sh-v${VERSION}.zip" .)
            fi
            
            if [ -d "templates_for_agents/${agent}/ps" ] && [ "$(ls -A templates_for_agents/${agent}/ps)" ]; then
              (cd "templates_for_agents/${agent}/ps" && tar -czf "../../../intent-kit-template-${agent}-ps-v${VERSION}.tar.gz" .)
              (cd "templates_for_agents/${agent}/ps" && zip -r "../../../intent-kit-template-${agent}-ps-v${VERSION}.zip" .)
            fi
          done
          
          # Also create a general templates archive
          if [ -d "templates" ] && [ "$(ls -A templates)" ]; then
            tar -czf "intent-kit-templates-v${VERSION}.tar.gz" templates/
            zip -r "intent-kit-templates-v${VERSION}.zip" templates/
          fi

      # Upload general templates
      - name: Upload general templates tar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: intent-kit-templates-v${{ env.ASSET_VERSION }}.tar.gz
          asset_name: intent-kit-templates-v${{ env.ASSET_VERSION }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload general templates zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: intent-kit-templates-v${{ env.ASSET_VERSION }}.zip
          asset_name: intent-kit-templates-v${{ env.ASSET_VERSION }}.zip
          asset_content_type: application/zip

      # Set outputs for the next job
      - name: Set outputs
        run: |
          echo "ASSET_VERSION=${{ env.ASSET_VERSION }}" >> $GITHUB_OUTPUT
        id: set-outputs

      # Upload agent-specific templates using GitHub Actions
      - name: List all template files
        shell: bash
        run: |
          echo "Generated template files:"
          ls -la intent-kit-template-*.zip intent-kit-template-*.tar.gz 2>/dev/null || echo "No template files found"

  # Create a separate job for uploading agent-specific templates
  upload-agent-templates:
    needs: create-templates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - asset_path: intent-kit-template-copilot-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-copilot-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-copilot-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-copilot-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-claude-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-claude-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-claude-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-claude-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-gemini-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-gemini-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-gemini-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-gemini-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-cursor-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-cursor-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-cursor-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-cursor-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-qwen-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-qwen-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-qwen-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-qwen-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-opencode-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-opencode-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-opencode-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-opencode-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-codex-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-codex-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-codex-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-codex-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-windsurf-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-windsurf-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-windsurf-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-windsurf-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-kilocode-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-kilocode-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-kilocode-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-kilocode-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-auggie-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-auggie-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-auggie-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-auggie-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-roo-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-roo-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-roo-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-roo-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-codebuddy-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-codebuddy-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-codebuddy-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-codebuddy-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-q-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-q-sh-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
          - asset_path: intent-kit-template-q-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_name: intent-kit-template-q-ps-v${{ needs.create-templates.outputs.ASSET_VERSION }}.zip
            asset_content_type: application/zip
    steps:
      - name: Upload agent-specific template
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.asset_path }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: ${{ matrix.asset_content_type }}
        if: ${{ needs.create-templates.outputs.ASSET_VERSION != '' }}  # Only run if ASSET_VERSION is set
        continue-on-error: true