name: Release Templates

on:
  release:
    types: [published]  # Trigger when a release is published

jobs:
  create-templates:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Create templates archives from project templates
        shell: bash
        run: |
          # Extract version from tag ref (removing 'refs/tags/' prefix and 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}  # Remove 'v' prefix if present
          # Create a full templates archive from the project's templates directory
          tar -czf intent-kit-templates-v${VERSION}.tar.gz templates/
          zip -r intent-kit-templates-v${VERSION}.zip templates/

      - name: Upload templates assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: intent-kit-templates-v${{ github.ref_name }}.tar.gz
          asset_name: intent-kit-templates-v${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload templates zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: intent-kit-templates-v${{ github.ref_name }}.zip
          asset_name: intent-kit-templates-v${{ github.ref_name }}.zip
          asset_content_type: application/zip